<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserStoreRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Models\Role;
use App\Models\User;

class UserController extends Controller
{
    /**
     * Block every method with the `\App\Middleware\AuthenticateAdmin` middleware except the index method.
     */
    public function __construct()
    {
        $this->middleware('auth.admin')->except(['index']);
    }

    /**
     * Return a list of the the Users.
     *
     */
    public function index()
    {
        $users = User::whereRelation('role', 'role', 'user')->get();
        return response()->json($users);
    }

    /**
     * Create a new User.
     */
    public function store(UserStoreRequest $request)
    {
        $data = $request->all();

        //generate a default password
        // Password is generated by default based on the first and last names of the User.
        $password = str_replace(' ', '.', strtolower($request->name));
        $data['password'] = bcrypt($password);

        // assign the user role id
        $userRoleId = Role::where('role', 'user')->pluck('id')->first();
        $data['role_id'] = $userRoleId;

        $user = User::create($data);

        return response()->json($user->load('role'));
    }

    /**
     * Return the specified User.
     */
    public function show(string $id)
    {
        $user = User::findOrFail($id);
        return response()->json($user);
    }

    /**
     * Update an existing user.
     */
    public function update(UserUpdateRequest $request, string $id)
    {
        $user = User::findOrFail($id);
        $user->update($request->only('name', 'email'));
        return response()->json($user);
    }

    /**
     * Remove the specified User.
     */
    public function destroy(string $id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return response(status: 204);
    }
}
